config/routes.rb
Rails.application.routes.draw do
  post 'projects/created'
  get 'projects/new'
  get 'projects/dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def created
    @project = Project.create(name: params[:name], description: params[:description], begin: params[:begin], end: params[:end], status: params[:status])
  end

  def new
    @project = Project.new
  end

  def dashboard
    if params[:status].present?
      @projects = Project.where('status = ?', params[:status])
    else
    @projects = Project.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1758aeb367.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/created.html.erb
<div class="container">
    <hr>
    <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2>
                Prohibited this operation from being saved:
            </h2>
            <br>
            <ul>
                <%= @project.errors.full_messages.each do %>
                <% end %>
            </ul>
            <div class="text-center">
                <hr> 
                <h3>Try again <%= link_to 'HERE', projects_new_path %>.</h3>
            </div>
        </div>
    <% else %>
    <div class="text-center">
        <h1>Your project was uploated!</h1>
    </div>
    <% end %>
    <hr>
    <h2 class="text-center">You can watch all your projects in the <%= link_to 'dashboard', projects_dashboard_path %>.</h2>
</div>

app/views/projects/dashboard.html.erb
<div class="container">
    <nav class="navbar navbar-light" id="search-nav">
			<p class="navbar-brand" id="search-ins">Search your proyect!</p>
			<form class="form-inline" id="search-form">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="status">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
	</nav>
	<hr>
	<h4 class="text-center">Please use only words "Porposal", "In progress" and "Finished" in your search.</h4>
	<hr>
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Name</th>
				<th scope="col">Description</th>
				<th scope="col">Begin date</th>
				<th scope="col">End date</th>
				<th scope="col">Status</th>
			</tr>
		</thead>
		<tbody>
			<% @projects.each do |project| %>
				<tr>
					<td><%= project.id %></td>
					<td><%= project.name %></td>
					<td><%= project.description %></td>
					<td><%= project.begin %></td>
					<td><%= project.end %></td>
					<td><%= project.status %></td>
				</tr>
			<% end %>	
		</tbody>
	</table>


</div>

app/views/projects/new.html.erb
<div class="container my-5">
    <form method="POST" action="/projects/created">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="form-group">
            <label for="formGroupExampleInput">Name</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Type the name." name="name">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Description</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Type the description of the proyect." name="description"></textarea>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Begin date</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Type the date when the proyect starts." name="begin">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">End date</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Type the date when the proyect ends." name="end">
        </div>
        <label for="formGroupExampleInput">Project Status</label>
        <select class="custom-select" name="status">
            <option value="Porposal" selected>Porposal</option>
            <option value="In progress">In progress</option>
            <option value="Finished">Finished</option>
        </select>
        <button type="submit" class="btn btn-primary my-5">Submit</button>
    </form>
    <h2 class="text-center">You can watch all your projects in the <%= link_to 'dashboard', projects_dashboard_path %>.</h2>
</div>

app/views/shared/_footer.html.erb
<div>
    <div class="card text-center">
    <div class="card-header">
        Hello!
    </div>
    <div class="card-body">
        <h5 class="card-title">A PP app.</h5>
        <p class="card-text">This is just an exercize for Desafio Latam.</p>
        <a href="https://github.com/PedroSebastiaan" class="btn btn-primary">My Github <i class="fab fa-github"></i></a>
    </div>
    <div class="card-footer text-muted">
        © Untitled. All rights reserved.
    </div>
    </div>
</div>

app/views/shared/_header.html.erb
<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <h2 class="super-title">My Gestor!</h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active mx-5 my-2">
                    <%= link_to 'Dashboard', projects_dashboard_path %>
                </li>
                <li class="nav-item active mx-5 my-2">
                    <%= link_to 'New Proyect', projects_new_path %>
                </li>
            </ul>
        </div>
    </nav>
</div>